### ISSUE TITLE
Add support for protocol 4 parameter update changes

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-ledger-app#49]
**Description**
Protocol version 4 (delegation protocol) adds new chain updates, which needs to supported by the ledger.

The sub tasks reflect the changes needed to support the new protocol version.

**Sub-tasks**
- [ ] add pool parameters update ([structure](https://github.com/Concordium/concordium-base/blob/17428df38e3844c977df2835ef3e32024fbd0043/haskell-src/Concordium/Types/Parameters.hs#L489))
  - This updates changes:
     - the commision rates for the L-pool
     - the ranges of commisions rates allowed for other pools
     - Minimum equity capital required for a new baker.
     - Maximum fraction of the total staked capital that a new baker can have.
     - The maximum leverage that a baker can have as a ratio of total stake to equity capital.
- [ ] add cooldown parameters update ([structure](https://github.com/Concordium/concordium-base/blob/17428df38e3844c977df2835ef3e32024fbd0043/haskell-src/Concordium/Types/Parameters.hs#L291))
  - This updates changes the cooldown period for pool owners and delegators. (when reducing stake/closing)
- [ ] add time parameters update ([structure](https://github.com/Concordium/concordium-base/blob/17428df38e3844c977df2835ef3e32024fbd0043/haskell-src/Concordium/Types/Parameters.hs#L366))
  - This updates changes the "mint rate per pay day", and the "reward period length".
- [ ] add support for mint distribution v1 (in which the mint rate per slot is removed)
- [ ] add support for update level 2 keys v1
  - add the new parameter updates, remove baker stake threshold
